## Preprocessing

In [1]:
import re
import pandas as pd
import matplotlib.pyplot as plt
import spacy
from tqdm.notebook import tqdm

In [2]:
tqdm.pandas()

In [3]:
nlp = spacy.load("en_core_web_sm")

In [4]:
df =pd.read_csv("../data/IMDB_Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
print(df.shape)
print(df.isnull().sum())
print(df["sentiment"].value_counts())

(50000, 2)
review       0
sentiment    0
dtype: int64
sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
df["label"] = df["sentiment"].map({
    "negative": 0,
    "positive": 1
})

df[["sentiment", "label"]].head()

  sentiment  label
0  positive      1
1  positive      1
2  positive      1
3  negative      0
4  positive      1

In [7]:
def clean_text(text:str) -> str:
    text = str(text).lower()

    text= re.sub(r"<.*?>"," ",text)

    text=re.sub(r"http\S+|www\S+"," ",text)

    text = re.sub(r"[^a-zA-Z\s]"," ",text)

    text = re.sub(r"\s+"," ", text).strip()

    return text

In [ ]:
NEGATION_WORDS ={"not","no","never","nor"}

In [ ]:
def spacy_preprocess(text: str) -> str:
    doc = nlp(text)
    tokens = []
    
    for token in doc:
        if token.is_space or token.is_punct:
            continue
        
        # stopword ise çıkar ama negation ise koru
        if token.is_stop and token.text not in NEGATION_WORDS:
            continue
        
        lemma = token.lemma_.strip()
        
        if not lemma:
            continue
        
        tokens.append(lemma)
    
    return " ".join(tokens)